### ISSUE TITLE
Dataset used in the project sharing

### ISSUE THREAD

**Issue by XYZ916829** [SANCHES-Pedro/Segmentation_3D_DeepLearning#5]
Hi, thanks for your sharing with your code. I'm doing the same research as your project.But I have not got the dataset to train my model. I'll appreciate it if you can share your dataset used in the project with me. 
Thank you!

**Comment by SANCHES-Pedro** [comment]
Hi, here it is:

https://public.kitware.com/Wiki/TubeTK/Data

**Comment by XYZ916829** [comment]
> Hi, here it is:
> 
> https://public.kitware.com/Wiki/TubeTK/Data

Thank you!
By the way, how do you generate the ground truth from "VascularNetwork.tre"?

**Comment by SANCHES-Pedro** [comment]
So, in this file you have the center line of the vessels as small spheres center coordinates and its radius, you just need to create a image where the voxels inside those spheres are equal to 1 and 0 otherwise.

**Comment by XYZ916829** [comment]
I made tubular reconstruction according to two adjacent centerline points and radii. The result is as follows, but it seems strange:
![QQ截图20190314185843](https://user-images.githubusercontent.com/14884056/54351871-793dc300-468b-11e9-87e5-b5c8656a6452.png)

**Comment by SANCHES-Pedro** [comment]
I think that's good... The visualization can change depending of the software you are using, but it seems right to me.

**Comment by Barcelona16** [comment]
How did u do that?
I draw all points in the three-dimensional space
![](https://raw.githubusercontent.com/Barcelona16/VesselSegmentation/master/TreOut.png)


Do u know the meaning of
```
PointDim = x y z r rn mn bn mk v1x v1y v1z v2x v2y v2z tx ty tz a1 a2 a3 red green blue alpha id
``` 
its from "VascularNetwork.tre", i know TubeTK(https://github.com/KitwareMedical/ITKTubeTK) can convert .tre to numpy but when i am build TubeTK and ITK ,but i got some difficult problems.So can u tell me a good way to solve .tre?
