### ISSUE TITLE
the original volume data and the groud truth

### ISSUE THREAD

**Issue by laolihaile** [SANCHES-Pedro/Segmentation_3D_DeepLearning#6]
I really appreciate your work. Your work is outstanding.
Could you please send me the original volume data and the groud truth of cerebrovascular MRA ?My email address is jihonglei62@gmail.com
Thank you very much!

**Comment by SANCHES-Pedro** [comment]
Hi, I just added a section in the readme with information about the dataset used and how to obtain it.

Thanks!

**Comment by laolihaile** [comment]
Thank you very much~~~

发送自 Windows 10 版邮件应用

发件人: Pedro Sanches
发送时间: 2020年1月7日 5:46
收件人: SANCHES-Pedro/Segmentation_3D_DeepLearning
抄送: laolihaile; Author
主题: Re: [SANCHES-Pedro/Segmentation_3D_DeepLearning] the original volumedata and the groud truth (#6)

Hi, I just added a section in the readme with information about the dataset used and how to obtain it.
Thanks!
